spring:
  datasource:
    url: jdbc:mysql://localhost:3306/agilitydb
    username: Admin
    password: password
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: agilitylt
      password: admin123

server:
  error:
    whitelabel:
      enabled: false

logging:
  level:
    com:
      agility:
        agilitylt:
          controler: TRACE